Cleaned up initd template.

diff --git a/templates/default/etcd.initd.erb b/templates/default/etcd.initd.erb
--- a/templates/default/etcd.initd.erb
+++ b/templates/default/etcd.initd.erb
@@ -1,103 +1,90 @@
 #!/bin/bash
 #
-# etcd      This shell script takes care of starting and stopping
-#             etcd
+# etcd      This shell script takes care of starting and stopping etcd
 #
 # chkconfig: 345 80 30
 # description:  etcd service registry
 
-# processname: etcd
-# pidfile: /var/run/etcd/etcd.pid
-
 # Source function library.
-. /lib/lsb/init-functions
-
-# Source etcd configuration
-if [ -f /etc/default/etcd ] ; then
- . /etc/default/etcd
-fi
+. /etc/rc.d/init.d/functions
 
 RETVAL=0
-prog="etcd"
+
+prog=`basename $0`
+etcd=/usr/local/bin/etcd
+
+lockfile=/var/lock/subsys/$prog
+pidfile=/var/run/$prog.pid
+
+STDOUT=/var/log/$prog.log
+STDERR=/var/log/$prog.err
+STOP_TIMEOUT=${STOP_TIMEOUT-10}
 
 start() {
- # Start daemons.
- echo -n $"Starting $prog: "
- PID=`pidof etcd`
- if [ ! -z $PID ]; then
-   return 2
- fi
- /usr/local/bin/etcd <%= @arguments.join("\\\n  ") %> > /var/log/etcd 2> /var/log/etcd.err &
- RETVAL=$?
- echo
- [ $RETVAL -eq 0 ] && touch /var/lock/etcd
- return $RETVAL
+  status_log=$(status -p $pidfile $prog)
+  RETVAL=$?
+  if [ $RETVAL -eq 0 ]; then
+    echo $status_log
+    return
+  fi
+
+  echo -n "Starting $prog:"
+  touch $pidfile
+
+  # Start daemon.
+  daemon \
+    --pidfile=$pidfile \
+    "{ /usr/local/bin/etcd \
+      <%= @arguments.join("\\\n  ") %> \
+      > $STDOUT 2> $STDERR &
+    }; echo \$! >| $pidfile" && success || failure
+
+  RETVAL=$?
+  [ $RETVAL -eq 0 ] && touch $lockfile
+  echo
 }
 
 stop() {
- # Stop daemons.
- echo -n $"Shutting down $prog: "
- PID=`pidof etcd`
- if [ ! -z $PID ]; then
-   kill -9 $PID
- fi
- RETVAL=$?
- echo
- [ $RETVAL -eq 0 ] && rm -f /var/lock/etcd
- return $RETVAL
+  status_log=$(status -p $pidfile $prog)
+  RETVAL=$?
+  if [ $RETVAL -ne 0 ]; then
+    echo $status_log
+    return
+  fi
+
+  echo -n $"Stopping $prog: "
+
+  # Stop daemon.
+  killproc -p ${pidfile} -d ${STOP_TIMEOUT} $etcd && success || failure
+  RETVAL=$?
+  echo
+  [ $RETVAL -eq 0 ] && rm -f $pidfile $lockfile
 }
 
-status() {
- PID=`pidof etcd`
- if [ ! -z $PID ]; then
-   echo "etcd is running running with pid $PID"
-   return 0
- else
-   echo "etcd is not running"
-   return 1
- fi
-}
-
-reload() {
- # Reload daemons.
- echo -n $"Reloading $prog: "
- kill -1 `pidof etcd`
- RETVAL=$?
- echo
- return $RETVAL
+restart() {
+  stop
+  sleep 1
+  start
+  RETVAL=$?
 }
 
 # See how we were called.
 case "$1" in
   start)
- start
- ;;
+    start
+    ;;
   stop)
- stop
- ;;
+    stop
+    ;;
   restart)
- stop
- start
- RETVAL=$?
- ;;
-  condrestart)
- if [ -f /var/lock/etcd ]; then
-     stop
-     start
-     RETVAL=$?
- fi
- ;;
+    restart
+    ;;
   status)
- status
- RETVAL=$?
- ;;
-  reload)
- reload
- RETVAL=$?
- ;;
+    status -p $pidfile $prog
+    ;;
   *)
- echo $"Usage: $0 {start|stop|restart|reload|condrestart|status}"
- exit 1
+    echo $"Usage: $0 {start|stop|restart|status}"
+    exit 1
 esac
 
 exit $RETVAL
